# This is an example yaml configuration for a metashape process

# Project

# If not a blank string, this will open an existing project at the path specified
load_project: "" #"/storage/forestuav/metashape_projects/set14_thin11/20200105T2215_set14_thin11_EmPo_USGSfirst.psx" #"/storage/collabs/nocco/metashape_projects/20200103T1816_09_20_2019_cherry.psx" # "/storage/forestuav/metashape_projects/through_classify/20200102T2034_01c_ChipsA.psx" "/storage/forestuav/metashape_projects/analysis7/20191204T1906_14_EmPo.psx" "/storage/forestuav/metashape_projects/full_test_1.6.0_22_subdivide_test/20200102T1221_01c_ChipsA.psx"

# The path to the directory of flight photos
# If multiple folders, set path to the top level above the photos?
# Photo folders should only include 1 set of calibration images if doing calibration
photo_path: "/storage/forestuav/imagery/missions_thinned/set14_120m_95_95_nadir_0ev_thin44" #"/storage/forestuav/imagery/missions_thinned/set14_120m_95_95_nadir_0ev_thin11"   #"/storage/forestuav/imagery/missions/14_EmPo_120m_95_95"

# This will save the project file psx and working files
project_path: "/storage/forestuav/metashape_projects/dev"

# Path for exports and processing log/benchmark data
output_path: "/storage/forestuav/metashape_outputs/dev"

# The identifier for the run. Will be used in naming output files. Recommended to include a photoset name and processing parameter set name
run_name: "set14_thin44_test_config_dum"

# CRS EPSG code that project outputs should be in
project_crs: "EPSG::26910"

# Whether to tell metashape to enable "fine-level task subdivision" which reduces memory use by breaking processing into independent chunks that are run in series. Assuming there's enough memory, it seems to run 10-20% faster by disabling subdividing.
subdivide_task: True

addGCPs:
    enabled: True
    gcp_crs: "EPSG::26910"  #4326  # CRS EPSG code of GCP coordinates
    marker_location_accuracy: 0.1 # accuracy of GCPs real-world coordinates, in meters
    marker_projection_accuracy: 8 # accuracy of the identified locations of the GCPs within the images, in pixels
    optimize_w_gcps_only: True # Optimize alignment using GCPs only: required for GCP locations to take precedence over photo GPS data

calibrateReflectance:
    enabled: False
    panel_path: "/storage/collabs/nocco/cherry/09_20_2019/RP04-1923118-OB.csv"     # example in: "/storage/calibration/RP04-1923118-OB.csv"
    use_reflectance_panels: True
    use_sun_sensor: True

alignPhotos:
    enabled: True
    downscale: 1
    adaptive_fitting: True

optimizeCameras:
    enabled: False
    adaptive_fitting: True

buildDenseCloud:
    enabled: False
    ## for depth maps
    downscale: 4 #default: 4
    filter_mode: Metashape.MildFiltering
    reuse_depth: False
    ## for dense cloud
    keep_depth: False
    ## for both
    max_neighbors: 100
    ## Dense cloud ground classification parameters
    classify: True     # Must be enabled if a digital terrain model (DTM) is needed either for orthomosaic or DTM export
    max_angle: 15.0
    max_distance: 1.0
    cell_size: 50.0
    ## Dense cloud export parameters
    export: True
    source: Metashape.DenseCloudData
    precision: 6
    format: Metashape.PointsFormatLAS
    classes: "ALL" # Must be a list. Or can set to "ALL" to use all points. An example of a specific class is: Metashape.PointClass.Ground


buildDem:
    ## Build DEM parameters
    enabled: False
    type: "both" # "DSM" or "DTM" or "both"
    ## Export DEM parameters
    export: True
    tiff_big: True
    tiff_tiled: False
    image_format: Metashape.ImageFormatTIFF
    nodata: -32767
    tiff_overviews: True


buildOrthomosaic:
    enabled: False
    surface: "DSM" # "DTM", "DSM", or "USGS"   # If USGS, you must use GCPs with accurate elevations (ideally extracted from the USGS DEM)
    usgs_dem_path: "dem_usgs/dem_usgs.tif"      # Needed if surface is USGS
    usgs_dem_crs: "EPSG::4269"                  # Needed if surface is USGS
    blending: Metashape.MosaicBlending
    fill_holes: True
    refine_seamlines: True
    # Export orthomosaic parameters
    export: True
    tiff_big: True
    tiff_tiled: False
    image_format: Metashape.ImageFormatTIFF
    nodata: -32767
    tiff_overviews: True