# This is an example yaml configuration for a metashape process

# Project
# This will save the project file psx and working files
project_path: "/storage/forestuav/metashape_projects/analysis1"

# The path to the directory of flight photos
# If multiple folders, set path to the top level above the photos?
# Photo folders should only include 1 set of calibration images if doing calibration
photo_path: "/storage/forestuav/imagery/missions/01c_ChipsA_120m_thinned22_subset"

# Path for exports and processing log/benchmark data
output_path: "/storage/forestuav/metashape_outputs/analysis1"

# The identifier for the set of photos (set to "%lookup%" to take from the photo path string. It would take element A if the photo folder is named A_B_C_D_E)
photoset_id: "%lookup%"  #"01c"

# The identifier for the location (set to "%lookup%" to take from the photo path string. It would take element B if the photo folder is named A_B_C_D_E)
location: "%lookup%" #"ChipsA"

# CRS EPSG code that project outputs should be in
project_crs: "EPSG::26910"



alignPhotos:
    accuracy: Metashape.HighAccuracy
    adaptive_fitting: True
    
optimizeCameras:
    adaptive_fitting: True
    
buildDepthMaps:
    quality: Metashape.MediumQuality
    filter: Metashape.MildFiltering
    reuse_depth: False
    max_neighbors: 100
    
buildDenseCloud:
    keep_depth: False
    max_neighbors: 100
    
classifyGroundPoints:
    max_angle: 15.0
    max_distance: 1.0
    cell_size: 50.0
  
buildDem:
    classes:
        - Metashape.PointClass.Ground # Must be a list, or can set to "ALL" to use all points
    source: Metashape.DenseCloudData
    
buildOrthomosaic:
    surface: Metashape.ElevationData
    blending: Metashape.MosaicBlending
    fill_holes: True
    refine_seamlines: True
    
exportDem:
    tiff_big: True
    tiff_tiled: False
    image_format: Metashape.ImageFormatTIFF
    projection: Metashape.CoordinateSystem("EPSG::32610")
    nodata: -32767
    tiff_overviews: True
    
exportOrthomosaic:
    tiff_big: True
    tiff_tiled: False
    image_format: Metashape.ImageFormatTIFF
    projection: Metashape.CoordinateSystem("EPSG::32610")
    tiff_overviews: True
    
exportPoints: 
    source: Metashape.DenseCloudData
    precision: 6
    format: Metashape.PointsFormatLAS
    projection: Metashape.CoordinateSystem("EPSG::32610")
    classes: "ALL" # Must be a list. Or can set to "ALL" to use all points. An example of a specific class is: Metashape.PointClass.Ground