# This is an example yaml configuration for a metashape process using the 
# Altum camera. Only deviations from the default settings are specified.
# Otherwise, metashape will just run the default settings.
# Configuration based on: https://agisoft.freshdesk.com/support/solutions/articles/31000148381-micasense-altum-processing-workflow-including-reflectance-calibration-in-agisoft-metashape-professi

# Project
# This will save the project file psx and working files
project_path: "/storage/forestuav/metashape_projects/analysis1"

# The path to the directory of flight photos
# If multiple folders, set path to the top level above the photos?
# Photo folders should only include 1 set of calibration images if doing calibration
photo_path: "/storage/forestuav/imagery/missions/01c_ChipsA_120m_thinned22_subset"

# Path for exports and processing log/benchmark data
output_path: "/storage/forestuav/metashape_outputs/analysis1"

# The identifier for the set of photos (set to "%lookup%" to take from the photo path string. It would take element A if the photo folder is named A_B_C_D_E)
photoset_id: "%lookup%"  #"01c"

# The identifier for the location (set to "%lookup%" to take from the photo path string. It would take element B if the photo folder is named A_B_C_D_E)
location: "%lookup%" #"ChipsA"

# CRS EPSG code that project outputs should be in
project_crs: "EPSG::26910"



alignPhotos:
    accuracy: Metashape.HighAccuracy
    adaptive_fitting: False

calibrateReflectance:
    panel_path: "calibration/RP04-1923118-OB.csv"
    use_reflectance_panels: True
    use_sun_sensor: True

optimizeCameras:
    adaptive_fitting: False
            
buildDepthMaps:
    quality: Metashape.MediumQuality
    filter: Metashape.AggressiveFiltering
    reuse_depth: False
    max_neighbors: 100

buildDenseCloud:
    keep_depth: False
    max_neighbors: 100
    
buildDem:
    classes: "ALL" # Must be a list, or can set to "ALL" to use all points
    source: Metashape.DenseCloudData
    # Interpolation changed from Altum guide to "enabled" (default)
    
buildOrthomosaic:
    surface: Metashape.ElevationData
    blending: Metashape.MosaicBlending
    fill_holes: True
    refine_seamlines: False
    
exportDem:
    tiff_big: True
    tiff_tiled: True
    image_format: Metashape.ImageFormatTIFF
    nodata: -32767
    tiff_overviews: True
    
exportOrthomosaic:
    tiff_big: True
    tiff_tiled: True
    image_format: Metashape.ImageFormatTIFF
    tiff_overviews: True
    